USE [master]
GO

/****** Object:  Database [budget4me]    Script Date: 11/7/2019 9:30:56 AM ******/
CREATE DATABASE [budget4me]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'budget4me', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\budget4me.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'budget4me_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\budget4me_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [budget4me] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [budget4me].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [budget4me] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [budget4me] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [budget4me] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [budget4me] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [budget4me] SET ARITHABORT OFF 
GO

ALTER DATABASE [budget4me] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [budget4me] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [budget4me] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [budget4me] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [budget4me] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [budget4me] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [budget4me] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [budget4me] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [budget4me] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [budget4me] SET  DISABLE_BROKER 
GO

ALTER DATABASE [budget4me] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [budget4me] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [budget4me] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [budget4me] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [budget4me] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [budget4me] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [budget4me] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [budget4me] SET RECOVERY FULL 
GO

ALTER DATABASE [budget4me] SET  MULTI_USER 
GO

ALTER DATABASE [budget4me] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [budget4me] SET DB_CHAINING OFF 
GO

ALTER DATABASE [budget4me] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [budget4me] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [budget4me] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [budget4me] SET QUERY_STORE = OFF
GO

ALTER DATABASE [budget4me] SET  READ_WRITE 
GO

